name: Golang Build and Test

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  build-test:
    name: Build and Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.17]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup up Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build and Test
        run:  go mod download

      - name: Testing application
        run: go test -cover ./...